### ISSUE TITLE
Broken URL in https://docs.saganize.com/get-started/

### ISSUE THREAD

**Issue by root-Manas** [Saganize/Solwave-kt#1]
The subdomain of https://saganize.com i.e docs.saganize.com has broken URL at 
https://docs.saganize.com/get-started/. The page has a forwarding link to Dashboard but gives 404 as the route used is incorrect. 
Used route : https://docs.saganize.com/get-started/dashboard/
Correct route: https://dashboard.saganize.com/
![Screenshot_2023-12-30-02-03-32-176_com android chrome-edit](https://github.com/Saganize/Solwave-kt/assets/97402139/b3146d05-5a26-4c1c-b1fe-3ae512850dfa)

**Comment by cdhiraj40** [comment]
Fixed it. Thanks!
